# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     container_name: postgres_db
#     restart: on-failure
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#       POSTGRES_DB: testDB
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

version: '3.9'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 4567:5432
    volumes:
      - ../apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=testDB


