spring:
    datasource:
        url: jdbc:postgresql://${DATABASE_URL}/${DATABASE_NAME}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    application:
        name: room-service

eureka:
    client:
        enabled: false
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always

security :
    allow:
        issuer: softdev_proj
    jwt:
        secret: 
            key : 45euytfkfrtyrtykfge65tdyfhkfthjgdrtdghhf
        expiration: 
            time : 86400000

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/